import type { Flashcard } from "../../types";

export const sc200Flashcards: Flashcard[] = [
  // -------------------------------------------------------------- operations
  {
    id: "sc200-c1",
    domainId: "operations",
    front: "Sentinel analytics rule types",
    back: "Scheduled (your KQL on your cadence), NRT (fixed one-minute runs), Microsoft security (promote other Microsoft alerts to incidents), Fusion (ML multi-stage attacks), Threat intelligence (match indicators), and Anomaly rules.",
  },
  {
    id: "sc200-c2",
    domainId: "operations",
    front: "Automation rule vs playbook",
    back: "Automation rules run natively in Sentinel on incident create/update and set properties (owner, severity, status, tags) or suppress incidents. Playbooks are Logic Apps that reach external services. Automation rules commonly call playbooks.",
  },
  {
    id: "sc200-c3",
    domainId: "operations",
    front: "Defender for Endpoint automation levels",
    back: "Full — remediate automatically. Semi — investigation runs, remediation waits for approval (variants scope approval to core folders or all folders). No automated response — investigation only.",
  },
  {
    id: "sc200-c4",
    domainId: "operations",
    front: "Which connector for which source?",
    back: "Windows Security Events via AMA for Windows event logs with DCR/XPath filtering. Syslog via AMA for Linux. CEF via AMA for network appliances. Logs Ingestion API plus a custom table for anything bespoke.",
  },
  {
    id: "sc200-c5",
    domainId: "operations",
    front: "What is attack surface reduction (ASR)?",
    back: "Defender for Endpoint rules that block common attack behaviours (Office child processes, LSASS credential theft, obfuscated scripts). Each rule can be Audit, Block, or Warn, with per-file or per-folder exclusions.",
  },
  {
    id: "sc200-c13",
    domainId: "operations",
    front: "Sentinel storage tiers",
    back: "Analytics tier — high performance, powers hunting, analytics rules, and incidents. Data lake tier — open Parquet format, up to 12 years retention, queried with KQL exploration and Python notebooks. Analytics data is mirrored into the lake as a single copy.",
  },
  {
    id: "sc200-c14",
    domainId: "operations",
    front: "What is a KQL job in the Sentinel data lake?",
    back: "A one-time or scheduled query that runs against the data lake tier and promotes its results into the analytics tier, making historical data usable by analytics rules and hunting.",
  },
  {
    id: "sc200-c15",
    domainId: "operations",
    front: "What are summary rules for?",
    back: "Scheduled aggregation of high-volume, low-value logs into a compact summary table, so you retain the analytical signal (daily counts, distinct values) without paying to keep every raw record in the analytics tier.",
  },
  {
    id: "sc200-c16",
    domainId: "operations",
    front: "What does SOC optimization recommend?",
    back: "Workspace-specific actions balancing cost and coverage — moving low-value tables to cheaper tiers, adding missing detections for threat scenarios, and retiring unused data sources.",
  },
  {
    id: "sc200-c17",
    domainId: "operations",
    front: "Alert tuning vs device group automation level",
    back: "Alert tuning suppresses or auto-resolves alerts matching conditions (device, title, file) so they stop generating noise. Automation level governs whether remediation of a raised alert needs approval. They solve different problems.",
  },
  {
    id: "sc200-c18",
    domainId: "operations",
    front: "How do you collect Windows events without an agent on every server?",
    back: "Windows Event Forwarding (WEF) to collector servers that run the Azure Monitor Agent, so only the collectors are agent-managed.",
  },
  {
    id: "sc200-c19",
    domainId: "operations",
    front: "How is Azure Activity collected into Sentinel at scale?",
    back: "Through diagnostic settings on each subscription. Assign an Azure Policy with DeployIfNotExists at the management group scope so current and future subscriptions are configured automatically.",
  },
  {
    id: "sc200-c20",
    domainId: "operations",
    front: "How do threat indicators reach Sentinel?",
    back: "Via a TAXII connector, the upload indicators API, or a platform integration — landing in the threat intelligence store where Threat Intelligence analytics rules match them against your telemetry.",
  },
  {
    id: "sc200-c21",
    domainId: "operations",
    front: "Required columns for a custom detection rule",
    back: "Timestamp, ReportId, and at least one entity column (DeviceId, DeviceName, AccountObjectId, SHA1, RecipientEmailAddress...) so the alert can be tied to an impacted asset and support response actions.",
  },
  {
    id: "sc200-c22",
    domainId: "operations",
    front: "Why does entity mapping matter in an analytics rule?",
    back: "It binds query columns to entity types, which is what powers the investigation graph, entity pages, alert grouping, and correlation. Without it, incidents are context-free.",
  },
  {
    id: "sc200-c23",
    domainId: "operations",
    front: "How should a playbook authenticate to Defender or Sentinel?",
    back: "With a managed identity on the Logic App, granted the needed roles or API permissions — no stored credentials, and automation is not tied to any individual's account.",
  },
  {
    id: "sc200-c24",
    domainId: "operations",
    front: "What is automatic attack disruption?",
    back: "Defender XDR uses very high-confidence signals to contain an in-progress attack automatically — disabling a compromised account or isolating a device — then surfaces the actions in the Action center for review or reversal.",
  },
  {
    id: "sc200-c25",
    domainId: "operations",
    front: "Sentinel anomaly rules and flighting",
    back: "Anomaly rules use built-in ML models with adjustable thresholds. You can run a customized copy in flighting mode alongside the production version, compare results, then promote it.",
  },
  {
    id: "sc200-c26",
    domainId: "operations",
    front: "How do you get bespoke application logs into a workspace?",
    back: "Define a custom table, create a data collection endpoint and data collection rule, then POST records with the Logs Ingestion API. The DCR can transform records on the way in.",
  },

  // ---------------------------------------------------------------- response
  {
    id: "sc200-c6",
    domainId: "response",
    front: "Golden Ticket containment",
    back: "Reset the krbtgt password twice, allowing replication between resets. Forged tickets are signed with the krbtgt key, so nothing short of rotating that key invalidates them.",
  },
  {
    id: "sc200-c7",
    domainId: "response",
    front: "Live response vs isolation vs investigation package",
    back: "Live response gives an interactive remote shell. Isolation cuts network access while keeping Defender connectivity. The investigation package is a downloadable forensic bundle (processes, network, autoruns, event logs).",
  },
  {
    id: "sc200-c8",
    domainId: "response",
    front: "Where do you find historical M365 user activity?",
    back: "Microsoft Purview Audit — sign-ins, file access, admin changes with user, timestamp, and IP. Audit (Premium) adds longer retention and high-value events such as MailItemsAccessed.",
  },
  {
    id: "sc200-c27",
    domainId: "response",
    front: "What is the Action center?",
    back: "The central queue of remediation actions across Defender XDR — pending approvals from semi-automated investigations, plus a history of completed actions that analysts can undo.",
  },
  {
    id: "sc200-c28",
    domainId: "response",
    front: "How do you remediate a phishing campaign already delivered?",
    back: "Threat Explorer or advanced hunting → select the messages → take action → soft delete or purge from every mailbox. Mail flow rules and Safe Links only affect future mail.",
  },
  {
    id: "sc200-c29",
    domainId: "response",
    front: "DCSync vs DCShadow",
    back: "DCSync abuses replication rights to pull password hashes from a DC as if it were another DC. DCShadow registers a rogue domain controller to inject malicious directory changes.",
  },
  {
    id: "sc200-c30",
    domainId: "response",
    front: "Defender for Cloud Apps: session vs file policy",
    back: "Session policies proxy live sessions via Conditional Access App Control to block download, copy, or print in real time. File policies scan content at rest and act afterwards (quarantine, remove sharing, apply label).",
  },
  {
    id: "sc200-c31",
    domainId: "response",
    front: "How do you remediate a high-risk user in Entra ID Protection?",
    back: "A risk-based Conditional Access policy that requires MFA and a secure password change. Self-remediation invalidates the stolen credential and automatically clears the risk state.",
  },
  {
    id: "sc200-c32",
    domainId: "response",
    front: "What is case management in the Defender portal?",
    back: "A workflow layer above incidents — group related incidents and evidence into a case with tasks, assignees, notes, and an audit trail, for investigations that outlive a single incident.",
  },
  {
    id: "sc200-c33",
    domainId: "response",
    front: "What does embedded Security Copilot do during triage?",
    back: "Summarises the incident, explains obfuscated scripts and command lines in plain language, identifies affected assets, and suggests response steps — speeding triage rather than replacing detections.",
  },
  {
    id: "sc200-c34",
    domainId: "response",
    front: "Which event proves an attacker read specific emails?",
    back: "MailItemsAccessed, an Audit (Premium) event. Sign-in logs prove authentication; MailItemsAccessed proves mailbox item access, which is what breach scoping requires.",
  },
  {
    id: "sc200-c35",
    domainId: "response",
    front: "What are Microsoft Graph activity logs good for?",
    back: "Seeing the actual Graph API calls made with a token — what an attacker did after authenticating. Sign-in logs show only the authentication event itself.",
  },
  {
    id: "sc200-c36",
    domainId: "response",
    front: "Defender XDR indicators (IoCs)",
    back: "Allow or block files (hash), IPs, URLs/domains, and certificates across onboarded devices. Blocking by hash is the fastest way to stop a known malicious binary estate-wide.",
  },
  {
    id: "sc200-c37",
    domainId: "response",
    front: "How should you close a benign-but-real incident?",
    back: "Classify it accurately (true positive with determination such as security testing, or benign positive) and add a scoped tuning rule. Never delete evidence or disable whole analytics rules.",
  },

  // ----------------------------------------------------------------- hunting
  {
    id: "sc200-c9",
    domainId: "hunting",
    front: "Core advanced hunting device tables",
    back: "DeviceProcessEvents (process creation), DeviceNetworkEvents (connections), DeviceLogonEvents (sign-ins), DeviceFileEvents (file activity), DeviceRegistryEvents (registry), DeviceEvents (miscellaneous), DeviceImageLoadEvents (module loads).",
  },
  {
    id: "sc200-c10",
    domainId: "hunting",
    front: "KQL: summarize vs distinct vs top",
    back: "summarize aggregates by grouping keys — use arg_max(Timestamp, *) for the latest full row per key. distinct returns unique column combinations. top N by Col returns N rows overall, not per group.",
  },
  {
    id: "sc200-c11",
    domainId: "hunting",
    front: "Email hunting tables",
    back: "EmailEvents (delivery, sender, recipient, verdict), EmailAttachmentInfo (attachment metadata and hashes), EmailUrlInfo (URLs in messages), UrlClickEvents (Safe Links click-throughs). Join on NetworkMessageId.",
  },
  {
    id: "sc200-c12",
    domainId: "hunting",
    front: "Identity hunting tables",
    back: "IdentityLogonEvents (authentication), IdentityDirectoryEvents (directory changes such as group membership), IdentityQueryEvents (LDAP/SAMR reconnaissance), IdentityInfo (account attributes for enrichment).",
  },
  {
    id: "sc200-c38",
    domainId: "hunting",
    front: "What is CloudAppEvents?",
    back: "The advanced hunting table for activity in SaaS apps monitored by Defender for Cloud Apps — acting account, IP, app, and activity type. Useful for tracing post-compromise cloud actions.",
  },
  {
    id: "sc200-c39",
    domainId: "hunting",
    front: "KQL: bin() and time series",
    back: "bin(Timestamp, 1h) rounds timestamps into fixed buckets so summarize can produce counts per interval, which render timechart then plots.",
  },
  {
    id: "sc200-c40",
    domainId: "hunting",
    front: "What is a hunting bookmark?",
    back: "A saved query result with its entities and analyst notes, preserved beyond the session. Bookmarks can be promoted into a new incident or attached to an existing one.",
  },
  {
    id: "sc200-c41",
    domainId: "hunting",
    front: "What is blast radius in a hunting graph?",
    back: "The set of assets and identities a compromised entity could reach through its relationships — showing lateral movement potential so containment can be prioritised.",
  },
  {
    id: "sc200-c42",
    domainId: "hunting",
    front: "What is Sentinel Graph?",
    back: "A relationship model over entities — users, devices, resources — that lets analysts traverse attack paths rather than reading isolated event rows.",
  },
  {
    id: "sc200-c43",
    domainId: "hunting",
    front: "Why use notebooks over the KQL editor?",
    back: "Notebooks run Python against data lake content, so you get machine learning libraries, statistical analysis, rich visualisation, and scheduled jobs that can summarise or promote data.",
  },
  {
    id: "sc200-c44",
    domainId: "hunting",
    front: "What is the Sentinel MCP server?",
    back: "An interface exposing Sentinel data and capabilities to AI agents and tools through the Model Context Protocol, so agent-driven hunting workflows can query context in a structured way.",
  },
  {
    id: "sc200-c45",
    domainId: "hunting",
    front: "What does threat analytics give you?",
    back: "Microsoft's in-product threat intelligence: tracked actors and campaigns correlated against your telemetry, showing whether you are exposed or impacted, plus recommended mitigations.",
  },
  {
    id: "sc200-c46",
    domainId: "hunting",
    front: "What makes a hunting query fit to become a detection rule?",
    back: "A bounded low-volume result set (no alert fatigue), mapped entities for investigability, a deterministic time window, and no random sampling with take.",
  },
];
